#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p):
    li = []
    for x in range(len(p)):
        x+=1
        i = 0
        for z in range(len(p)):
            if p[z]==x:
                i = z+1
                break
        t = i        
        for z in range(len(p)):
            if p[z]==t:
                li.append(z+1)
                break
    return li
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
